import React, { useState } from 'react';
import { BookOpen, Plus, ShieldCheck, Search, FileText, Trash2, CheckCircle2, Sparkles, Filter, Edit3, X, AlertCircle } from 'lucide-react';
import { KnowledgeDocument } from '../types/bharatSupport';

interface KnowledgeBaseViewProps {
  documents: KnowledgeDocument[];
  onAddDocument: (title: string, category: string, content: string) => void;
  onUpdateDocument?: (id: string, title: string, category: string, content: string) => void;
  onDeleteDocument: (id: string) => void;
}

export const KnowledgeBaseView: React.FC<KnowledgeBaseViewProps> = ({
  documents,
  onAddDocument,
  onUpdateDocument,
  onDeleteDocument,
}) => {
  const [searchQuery, setSearchQuery] = useState('');
  const [selectedCategory, setSelectedCategory] = useState<string>('all');
  const [isAddingNew, setIsAddingNew] = useState(false);
  const [newTitle, setNewTitle] = useState('');
  const [newCategory, setNewCategory] = useState('Policies');
  const [newContent, setNewContent] = useState('');
  const [formError, setFormError] = useState<string | null>(null);

  // Edit document state
  const [editingDoc, setEditingDoc] = useState<KnowledgeDocument | null>(null);
  const [editTitle, setEditTitle] = useState('');
  const [editCategory, setEditCategory] = useState('');
  const [editContent, setEditContent] = useState('');

  // Semantic search simulation
  const [retrievalQuery, setRetrievalQuery] = useState('');
  const [retrievedResult, setRetrievedResult] = useState<{ doc: KnowledgeDocument; score: number } | null>(null);

  const categories = Array.from(new Set(documents.map((d) => d.category)));

  const filteredDocs = documents.filter((doc) => {
    const matchesSearch =
      doc.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      doc.content.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesCategory = selectedCategory === 'all' || doc.category === selectedCategory;
    return matchesSearch && matchesCategory;
  });

  const handleCreateSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);
    if (!newTitle.trim() || !newContent.trim()) {
      setFormError('Both Title and Document Content are required for indexing.');
      return;
    }
    onAddDocument(newTitle.trim(), newCategory, newContent.trim());
    setNewTitle('');
    setNewContent('');
    setIsAddingNew(false);
  };

  const handleStartEdit = (doc: KnowledgeDocument) => {
    setEditingDoc(doc);
    setEditTitle(doc.title);
    setEditCategory(doc.category);
    setEditContent(doc.content);
    setFormError(null);
  };

  const handleEditSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);
    if (!editTitle.trim() || !editContent.trim()) {
      setFormError('Both Title and Document Content are required to update.');
      return;
    }
    if (editingDoc && onUpdateDocument) {
      onUpdateDocument(editingDoc.id, editTitle.trim(), editCategory, editContent.trim());
    }
    setEditingDoc(null);
  };

  const handleTestRetrieval = () => {
    if (!retrievalQuery.trim() || documents.length === 0) return;
    const qWords = retrievalQuery.toLowerCase().split(/\s+/).filter(Boolean);

    // Calculate score based on keyword overlaps in title and content
    let bestDoc = documents[0];
    let bestScore = 0;

    for (const d of documents) {
      const textToSearch = `${d.title} ${d.category} ${d.content}`.toLowerCase();
      let matchCount = 0;
      for (const w of qWords) {
        if (textToSearch.includes(w)) matchCount++;
      }
      const score = Math.min(0.98, 0.70 + (matchCount / Math.max(qWords.length, 1)) * 0.28);
      if (matchCount > bestScore || (matchCount === bestScore && score > 0.85)) {
        bestScore = matchCount;
        bestDoc = d;
      }
    }

    setRetrievedResult({
      doc: bestDoc,
      score: bestScore > 0 ? Math.min(0.96, 0.75 + bestScore * 0.05) : 0.62,
    });
  };

  return (
    <div className="max-w-7xl mx-auto px-4 py-8">
      {/* Title */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-8">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="bg-emerald-100 text-emerald-800 text-xs font-bold px-2 py-0.5 rounded">
              03 Knowledge Retrieval & Reasoning
            </span>
            <span className="text-xs text-slate-500 font-medium">
              Grounding & Vector Retrieval (pgvector) for Zero-Hallucination
            </span>
          </div>
          <h1 className="font-display text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">
            Verified SMB Knowledge Base
          </h1>
          <p className="text-sm text-slate-600 mt-0.5">
            Every customer reply generated by BharatSupport AI is mathematically grounded in these verified sources.
          </p>
        </div>

        <button
          onClick={() => {
            setIsAddingNew(!isAddingNew);
            setEditingDoc(null);
          }}
          className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold rounded-lg shadow-sm transition-all self-start sm:self-auto"
        >
          <Plus className="w-4 h-4" />
          <span>Add Knowledge Document</span>
        </button>
      </div>

      {/* Add Document Drawer / Form */}
      {isAddingNew && (
        <form
          onSubmit={handleCreateSubmit}
          className="bg-white rounded-2xl border border-blue-200 p-6 shadow-md mb-8 animate-fade-in"
        >
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-display text-base font-bold text-slate-900 flex items-center gap-2">
              <BookOpen className="w-4 h-4 text-blue-600" />
              <span>New Knowledge Document (Policy, Fee Sheet, FAQ)</span>
            </h3>
            <div className="flex items-center gap-2">
              <button
                type="button"
                onClick={() => {
                  setNewTitle('Diwali Flash Sale');
                  setNewCategory('Policies');
                  setNewContent('Use coupon code FESTIVE50 for 50% discount on bootcamps.');
                }}
                className="text-xs bg-amber-50 hover:bg-amber-100 text-amber-800 font-semibold px-2.5 py-1 rounded border border-amber-200 transition-colors"
              >
                ⚡ Quick Fill: Diwali Flash Sale
              </button>
              <button
                type="button"
                onClick={() => setIsAddingNew(false)}
                className="text-slate-400 hover:text-slate-600"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
          </div>

          {formError && (
            <div className="mb-4 p-3 rounded-lg bg-rose-50 border border-rose-200 text-rose-800 text-xs flex items-center gap-2">
              <AlertCircle className="w-4 h-4 shrink-0 text-rose-600" />
              <span>{formError}</span>
            </div>
          )}

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">Document Title</label>
              <input
                type="text"
                value={newTitle}
                onChange={(e) => setNewTitle(e.target.value)}
                placeholder="e.g. D2C Return, Refund & Cancellation Policy 2026"
                className="w-full px-3.5 py-2 bg-slate-50 border border-slate-200 rounded-lg text-xs sm:text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-blue-600/30"
                required
              />
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">Category</label>
              <select
                value={newCategory}
                onChange={(e) => setNewCategory(e.target.value)}
                className="w-full px-3.5 py-2 bg-slate-50 border border-slate-200 rounded-lg text-xs sm:text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-blue-600/30"
              >
                <option value="Fee Sheets & Admission">Fee Sheets & Admission</option>
                <option value="Logistics & Orders">Logistics & Orders</option>
                <option value="Policies">Policies & Refunds</option>
                <option value="Account & Security">Account & Security</option>
                <option value="Operations">Operations & Escalations</option>
                <option value="Product Catalog">Product Catalog</option>
              </select>
            </div>
          </div>

          <div className="mb-4">
            <label className="block text-xs font-semibold text-slate-700 mb-1">
              Document Text / Policy Clauses
            </label>
            <textarea
              rows={4}
              value={newContent}
              onChange={(e) => setNewContent(e.target.value)}
              placeholder="Paste exact verified facts, bullet points, numbers, refund windows, batch timings..."
              className="w-full px-3.5 py-2 bg-slate-50 border border-slate-200 rounded-lg text-xs sm:text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-blue-600/30"
              required
            />
          </div>

          <div className="flex justify-end gap-2">
            <button
              type="button"
              onClick={() => setIsAddingNew(false)}
              className="px-4 py-2 text-xs font-medium text-slate-600 hover:text-slate-900"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold rounded-lg shadow-sm"
            >
              Save & Index to Vector DB
            </button>
          </div>
        </form>
      )}

      {/* Edit Document Modal / Drawer */}
      {editingDoc && (
        <form
          onSubmit={handleEditSubmit}
          className="bg-white rounded-2xl border border-amber-300 p-6 shadow-md mb-8 animate-fade-in"
        >
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-display text-base font-bold text-slate-900 flex items-center gap-2">
              <Edit3 className="w-4 h-4 text-amber-600" />
              <span>Edit Document: {editingDoc.title}</span>
            </h3>
            <button
              type="button"
              onClick={() => setEditingDoc(null)}
              className="text-slate-400 hover:text-slate-600"
            >
              <X className="w-4 h-4" />
            </button>
          </div>

          {formError && (
            <div className="mb-4 p-3 rounded-lg bg-rose-50 border border-rose-200 text-rose-800 text-xs flex items-center gap-2">
              <AlertCircle className="w-4 h-4 shrink-0 text-rose-600" />
              <span>{formError}</span>
            </div>
          )}

          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4 mb-4">
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">Document Title</label>
              <input
                type="text"
                value={editTitle}
                onChange={(e) => setEditTitle(e.target.value)}
                className="w-full px-3.5 py-2 bg-slate-50 border border-slate-200 rounded-lg text-xs sm:text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-blue-600/30"
                required
              />
            </div>
            <div>
              <label className="block text-xs font-semibold text-slate-700 mb-1">Category</label>
              <input
                type="text"
                value={editCategory}
                onChange={(e) => setEditCategory(e.target.value)}
                className="w-full px-3.5 py-2 bg-slate-50 border border-slate-200 rounded-lg text-xs sm:text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-blue-600/30"
                required
              />
            </div>
          </div>

          <div className="mb-4">
            <label className="block text-xs font-semibold text-slate-700 mb-1">Document Content</label>
            <textarea
              rows={5}
              value={editContent}
              onChange={(e) => setEditContent(e.target.value)}
              className="w-full px-3.5 py-2 bg-slate-50 border border-slate-200 rounded-lg text-xs sm:text-sm text-slate-900 focus:outline-none focus:ring-2 focus:ring-blue-600/30 font-mono"
              required
            />
          </div>

          <div className="flex justify-end gap-2">
            <button
              type="button"
              onClick={() => setEditingDoc(null)}
              className="px-4 py-2 text-xs font-medium text-slate-600 hover:text-slate-900"
            >
              Cancel
            </button>
            <button
              type="submit"
              className="px-4 py-2 bg-amber-600 hover:bg-amber-700 text-white text-xs font-semibold rounded-lg shadow-sm"
            >
              Update & Re-Index
            </button>
          </div>
        </form>
      )}

      {/* RAG Vector Retrieval Playground */}
      <div className="bg-gradient-to-br from-slate-900 to-blue-950 text-white rounded-2xl p-6 shadow-sm mb-8">
        <div className="flex items-center gap-2 mb-2">
          <Sparkles className="w-4 h-4 text-emerald-400" />
          <h3 className="font-display text-base font-bold">
            Simulate pgvector Semantic Retrieval (RAG)
          </h3>
        </div>
        <p className="text-xs text-blue-200 mb-4">
          Test which verified knowledge document chunk is retrieved when a customer asks a question:
        </p>

        <div className="flex gap-2">
          <input
            type="text"
            value={retrievalQuery}
            onChange={(e) => setRetrievalQuery(e.target.value)}
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                e.preventDefault();
                handleTestRetrieval();
              }
            }}
            placeholder="e.g. password reset, weekend batch fee, refund timeline for UPI, metro delivery time..."
            className="flex-1 px-3.5 py-2 bg-white/10 border border-white/20 rounded-xl text-xs sm:text-sm text-white placeholder:text-blue-300 focus:outline-none focus:ring-2 focus:ring-blue-400"
          />
          <button
            onClick={handleTestRetrieval}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-500 text-white text-xs font-semibold rounded-xl shrink-0"
          >
            Retrieve Chunk
          </button>
        </div>

        {retrievedResult && (
          <div className="mt-4 p-4 rounded-xl bg-white/10 border border-white/15 text-xs text-blue-100 animate-fade-in">
            <div className="flex items-center justify-between mb-1.5 font-semibold text-white">
              <span>Matched Document: {retrievedResult.doc.title}</span>
              <span className="text-[10px] text-emerald-300 font-mono">
                Similarity: {(retrievedResult.score * 100).toFixed(1)}% match
              </span>
            </div>
            <p className="whitespace-pre-line text-blue-200 text-[11px] leading-relaxed line-clamp-3">
              {retrievedResult.doc.content}
            </p>
          </div>
        )}
      </div>

      {/* Search & Category Filter Bar */}
      <div className="bg-white rounded-xl border border-slate-200 p-3 sm:p-4 mb-6 shadow-xs flex flex-col sm:flex-row items-center justify-between gap-3">
        <div className="relative flex-1 w-full">
          <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search policies, fee sheets, delivery SLAs..."
            className="w-full pl-9 pr-3.5 py-2 text-xs sm:text-sm bg-slate-50 border border-slate-200 rounded-lg text-slate-900 focus:outline-none focus:ring-2 focus:ring-blue-600/30"
          />
        </div>

        <div className="flex items-center gap-1.5 w-full sm:w-auto overflow-x-auto pb-1 sm:pb-0">
          <button
            onClick={() => setSelectedCategory('all')}
            className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition-colors ${
              selectedCategory === 'all'
                ? 'bg-blue-600 text-white'
                : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
            }`}
          >
            All Categories ({documents.length})
          </button>
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setSelectedCategory(cat)}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold whitespace-nowrap transition-colors ${
                selectedCategory === cat
                  ? 'bg-blue-600 text-white'
                  : 'bg-slate-100 text-slate-600 hover:bg-slate-200'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      {/* Documents Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {filteredDocs.map((doc) => (
          <div
            key={doc.id}
            className="bg-white rounded-2xl border border-slate-200 p-5 shadow-xs hover:border-blue-300 transition-colors flex flex-col justify-between"
          >
            <div>
              <div className="flex items-start justify-between gap-2 mb-2">
                <span className="text-[11px] font-bold text-blue-700 bg-blue-50 px-2 py-0.5 rounded border border-blue-100">
                  {doc.category}
                </span>
                <div className="flex items-center gap-1 text-[11px] text-emerald-700 font-semibold">
                  <CheckCircle2 className="w-3.5 h-3.5 text-emerald-600" />
                  <span>Verified & Indexed</span>
                </div>
              </div>

              <h3 className="font-display text-base font-bold text-slate-900 mb-3">
                {doc.title}
              </h3>

              <div className="bg-slate-50 rounded-xl p-3.5 border border-slate-100 text-xs text-slate-700 leading-relaxed whitespace-pre-line mb-4 font-mono max-h-44 overflow-y-auto">
                {doc.content}
              </div>
            </div>

            <div className="pt-3 border-t border-slate-100 flex items-center justify-between text-[11px] text-slate-400">
              <span>Indexed: {doc.lastUpdated}</span>
              <div className="flex items-center gap-2">
                <button
                  onClick={() => handleStartEdit(doc)}
                  className="text-slate-500 hover:text-blue-600 p-1 transition-colors flex items-center gap-1"
                  title="Edit document"
                >
                  <Edit3 className="w-3.5 h-3.5" />
                  <span className="text-[10px] font-semibold">Edit</span>
                </button>
                <button
                  onClick={() => {
                    if (confirm(`Remove "${doc.title}" from knowledge base?`)) {
                      onDeleteDocument(doc.id);
                    }
                  }}
                  className="text-slate-400 hover:text-rose-600 p-1 transition-colors"
                  title="Delete document"
                >
                  <Trash2 className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
